kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-metrics-exporter
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - oauths
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - proxies
  - clusterversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterroles
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterroles/finalizers
  verbs:
    - update
- apiGroups:
    - user.openshift.io
  resources:
    - groups
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - user.openshift.io
  resources:
    - groups/finalizers
  verbs:
    - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch